### ISSUE TITLE
How to send notification to another user's slack workspace 

### ISSUE THREAD

**Issue by dsharma522** [trycourier/courier-python#46]
I want to send slack notification (message as an app to another workspace).

1. I have created a slack app as `slack_app`
2. I have installed `slack_app` into my own_workspace as `own_ws`.
3. A external users say `user_x` has installed my slack app into their workspace. 

I want to automate this sending notification business using third parties for example, using [courier](https://www.courier.com/blog/courier-live-sending-notifications-via-slack/) or using something else library.

I have webhook url of `user_x`'s slack workspace which i caught during oauth installation and that is something can be used to send messages but how to automate this sending notification via some third party.

How we can send notification/message into another workspace ? I did research a bit but could not find relevant information anywhere. 

Sorry that creating this an issue, It is Question/discussion label. I could not find anything, hence posted here for some positive response.

**Comment by dsinghvi** [comment]
@dsharma522 closing this issue since it's been open for a long time! feel free to reopen.
