### ISSUE TITLE
Tenants client `list_` method always returns a `TenantListResponse` with an empty `items`

### ISSUE THREAD

**Issue by ryancausey** [trycourier/courier-python#82]
I am attempting to list my tenants, but the issue I am running into is that the `TenantListResponse` has an empty `items` in the response. It appears it is supposed to return a list of `Tenant` objects in the `items` attribute, but this is always empty. This is the case even when the `has_more` attribute is `True`, indicating the list was paginated and I can retrieve more tenants. Passing the resulting cursor also returns a `TenantListResponse` with an empty `items`.

```python
>>> client = Courier(authorization_token=courier_api_key)
>>> tenants = client.tenants.list_()
>>> tenants
TenantListResponse(cursor='MTcxODMxODc1MzkyMSxNR0prWlRZME5EQXRZV1prTXkwMFpHRXpMVGd4WkdRdE1tVmtZamcxT1RoaE9EaGlMM1JsYzNRdmIzSm5YelZLYTFocVNsWmtRMlpZWTJKM1NFOUVVazFNVmpKcmFFRnNjQT09', has_more=True, items=[], next_url='/tenants?cursor=MTcxODMxODc1MzkyMSxNR0prWlRZME5EQXRZV1prTXkwMFpHRXpMVGd4WkdRdE1tVmtZamcxT1RoaE9EaGlMM1JsYzNRdmIzSm5YelZLYTFocVNsWmtRMlpZWTJKM1NFOUVVazFNVmpKcmFFRnNjQT09', url='/tenants', type='list')
>>> tenants.has_more
True
>>> tenants.items
[]
```

**Comment by dsinghvi** [comment]
@ryancausey thanks for filing this issue, we'll try to reproduce this on our end.

**Comment by ryancausey** [comment]
I can no longer reproduce this issue as of 06/23/2024, so I will close it.
